---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "man/figures/README-",
  out.width = "100%"
)
```
# sometype

<!-- badges: start -->
<!-- badges: end -->

This is a dependency-free experimental implementation of Option & Result types in base R. The API draws most of its inspiration from the [Rust](https://www.rust-lang.org/) standard library ([Option<T>](https://doc.rust-lang.org/std/option/), [Result<T, E>](https://doc.rust-lang.org/std/result/)). 

Other packages have done something for `Option` ([maybe](https://cran.r-project.org/package=maybe), [optional](https://cran.r-project.org/package=optional), among others), but I am unaware of any `Result` implementations in R (please correct me!).

## Installation

``` r
# install.packages("remotes")
remotes::install_github("snystrom/sometype")
```

## R Option<T>

`sometype` implements an `Option` S3 type:

Options are useful for wrapping values that can be missing (`None`) or real (`Some`), forcing the user to handle them explicitly.

```{r, error=TRUE}
library(sometype)

div0 <- function(x, y) {
  if (y == 0) {
    return(none)
  } 

  some(x/y)
}

answer <- div0(10,2)

# This is not allowed
answer > 2
```

```{r}
# Explicitly handling the option allows comparison
unwrap(answer) > 2
```

```{r}
# Syntactic sugar allows auto-unwrapping 
# (this is probably a bad idea and I'll kill this later)
answer <- !div0(10,2)
answer == 5
```

```{r, error = TRUE}
# Unwrap(none) will crash
answer <- !div0(10,0)
```

### Option<T> constructors

Users can manually build `Option<T>` objects using `some()` and `none`, or by using the `option()` constructor.

```{r}
# Values become Some()
option(5)
```

```{r}
# Missing values become None
option(NULL)
```

```{r}
# Options can be manually constructed
some(5) 
```

```{r}
# none is a special keyword export!
none
```

Users can provide custom predicates to produce `Option<None>` from values.
```{r}
gt_five <- function(x) {
  x > 5
}

option(10, list(gt_five))
```

### Handling Options

```{r}
# Return a default value on None
unwrap_or(div0(1,0), 0)
```

```{r}
# Do a custom behavior on None
oh_no <- function() {
  print("Oh No!")
}

unwrap_or_else(div0(1,0), oh_no)
```

```{r, error=TRUE}
# Throw a specific error on None
expect(div0(1,0), "I divided by zero!")
```

## Result<T,E>

### Error

```{r}
e <- error("some_error", "a custom message")
e
```

```{r, error = TRUE, eval=FALSE}
stop(e)
#> Error: a custom message
```

### Ok(T)
```{r}
ok(5)
```

```{r}
# results cannot nest (this differs from Rust!)
ok(ok(5)) == ok(5)
```

Results can be unwrapped just like Options.
```{r}
unwrap(ok(5))
```

### Results are incompatible with base methods
```{r, error = TRUE}
ok(5) + 1
```

```{r, error = TRUE}
as.integer(ok(5))
```

But can be compared with other Results
```{r}
ok(1) == ok(1)
```

```{r}
ok(1) == ok(2)
```

```{r, error = TRUE}
ok(1) == 1
```

```{r}
error() == error()
```

```{r}
error() == ok(1)
```

## Use Cases

### Alternative to tryCatch

Use with methods that do not natively support `sometype`.
```{r}
may_fail <- function(x) {
  if (x > 10) {
    stop("failure!")
  } else {
    return("success!")
  }
}
```

```{r, error=TRUE}
may_fail(5)
```

```{r, error=TRUE}
may_fail(11)
```

```{r}
try_result(may_fail(5))
```

```{r}
try_result(may_fail(11))
```

Catch into custom error types
```{r}
try_result(may_fail(11), .err_type = "a_custom_error")
```

### Refactors

Consider a situation where two methods are owned by an external source (`method_one`, `method_two`), that we wrap into our own handler, `nested_may_fail`.

```{r}
# Pretend this is from another package, we don't control whether it `stop`s
method_one <- function() {
  stop("method one failed")
}

# Pretend this is from another package, we don't control whether it `stop`s
method_two <- function() {
  stop("method two failed")
}

# This is our function, we only control how to handle the outputs
nested_may_fail <- function(x = TRUE) {
  if (x) {
    method_one()
  } else {
    method_two()
  }
}
```

```{r, error = TRUE}
nested_may_fail(TRUE)
```

```{r, error = TRUE}
nested_may_fail(FALSE)
```

If we control `nested_may_fail` but do not control the implementations of `method_one` or `method_two`, it is difficult to handle each method failure without writing `tryCatch` logic in-place for each method.
```{r}
handle_method_one_fail <- function(e) {
  message('caught failure one')
}

handle_method_two_fail <- function(e) {
  message('caught failure two')
}

nested_may_fail <- function(x = TRUE) {
  if (x) {
    tryCatch(method_one(),
             error = handle_method_one_fail
             )
  } else {
    tryCatch(method_two(),
             error = handle_method_two_fail
             )
  }
}

nested_may_fail()
```

Using `result`s and `error`s allows us to take ownership of errors and centralize how we handle the output.
```{r}

nested_may_fail <- function(x = TRUE) {
  if (x) {
    try_result(method_one(), .err_type = "method_one")
  } else {
    try_result(method_two(), .err_type = "method_two")
  }
}
```

```{r}
result <- nested_may_fail()

if (is_err(result)) {
  switch(result$error_type,
         method_one = message("caught failure one"),
         method_two = message("caught failure two"),
         generic_result_error = stop(result),
         stop("Unknown error type")
         )
} else {
  result <- unwrap(result)
}

# Continue with success logic
```

**Experimental: `match_result()`**

This is just syntactic sugar over `switch` like above, but supports an `ok` entry.
```{r}
result <- nested_may_fail()
output <- match_result(result,
             method_one = message("caught failure one"),
             method_two = message("caught failure two"),
             generic_result_error = stop(result),
             ok = unwrap(result)
             )
```

## Conversion Methods

### Option to Result
```{r}
ok_or(some(1))
```

```{r}
ok_or(none)
```

### Result to Option

```{r}
as_option(ok(1))
```

```{r}
as_option(error())
```

```{r}
as_option(
  try_result({
    stop("oh no!")
  })
)
```

### Differences from prior implementations

For better or for worse, R's type system allows amazing flexibility often allowing things to "just work". This however doesn't work well for a data structure (like an `option`) that we want to **force** users to handle.

`sometype`'s `option`s are designed for minimal compatability with the rest of the R ecosystem. The goal is that users **must** handle `options` before actual work can be done on them. Other packages do not implement this behavior.

To demonstrate:
```{r}
optional_five <- optional::option(5)
just_five <- maybe::just(5)
some_five <- sometype::some(5)
```

`optional` propagates the `option` type, but allows computation.
```{r}
optional_five + 1
```

```{r}
optional::none + 1
```

`maybe` errors on some operations.
```{r, error = TRUE}
# This errors! Good!
just_five + 1
```

But supports others:
```{r}
# Oh no!
just_five[1]
```

```{r}
# Oh no!
as.character(just_five)
```

`sometype` should fail on all base R operations
```{r, error = TRUE}
some_five + 1
```

```{r, error = TRUE}
some_five[1]
```

```{r, error = TRUE}
as.character(some_five)
```

If an `option` or `result` can be provided as a valid argument to a function that does not handle them and produce no errors: that's probably a [bug](https://github.com/snystrom/sometype/issues).

## TODO's
* Still some weirdness with the `error` impl, it could be better. (should we store & throw the original condition somehow?)
* I'm not sold whether S3 is the right impl. May test an R6 version so it is more clear what methods are allowed on Result vs Option, etc.
* should `match_result` support generic error fallback?
